global_frame: map
rolling_window: true
max_obstacle_width: 8.0
max_obstacle_height: 8.0
width: 7
height: 7

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
