# more on http://wiki.ros.org/navigation/Tutorials/RobotSetup

local_costmap:
  update_frequency: 10.0
  publish_frequency: 4.0
  transform_tolerance: 0.5 # [s]
  
  rolling_window: true
  width: 8.0
  height: 8.0
  resolution: 0.10
  
  global_frame: map
  robot_base_frame: base_link
  map_topic: /traversability_occ_map
  
  plugins:
    -
     name: static
     type: "costmap_2d::StaticLayer"
    - 
     name: obstacle_layer
     type: "costmap_2d::ObstacleLayer"  
    -
     name: inflation_layer
     type: "costmap_2d::InflationLayer"

  virtual_obstacles:
    observation_sources: laser_scan_sensor
    
  obstacle_layer:
    enabled: true
    observation_sources: laser_scan_sensor 
    laser_scan_sensor:
      data_type: 'LaserScan'
      topic: scan
      marking: true
      clearing: true
      min_obstacle_height: -100.0
      max_obstacle_height: 100.0
      observation_persistence: 0.4
      inf_is_valid: true   

  inflation_layer:
    enabled: true
    observation_sources: laser_scan_sensor
    inflation_radius: 0.15
